name: Quality

on: push

jobs:
    phpunit:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Setup PHP with pecl extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: composer:v2
            -   name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    php_version: 8.0
                    args: --prefer-dist
                    quiet: ~
            -   name: PhpUnit
                run: bin/phpunit

    cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Setup PHP with pecl extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: composer:v2
            -   name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    php_version: 8.0
                    args: --prefer-dist
                    quiet: ~
            -   name: Cs-Fixer
                run: |
                    wget -q https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                    chmod a+x php-cs-fixer
                    PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer check src

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                phpstan-level: [ 3, 5, 7, 8 ]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Setup PHP with pecl extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: composer:v2
            -   name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    php_version: 8.0
                    args: --prefer-dist
                    quiet: ~
            -   name: PHPStan
                run: bin/phpstan analyze --level=${{ matrix.phpstan-level }} src

    infection:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Setup PHP with pecl extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: composer:v2
            -   name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    no-progress: true
                    prefer-dist: true
            -   name: Infection
                run: |
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar.asc
                    chmod +x infection.phar
                    ./infection.phar
