name: Quality

on: push

jobs:
    quality:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [ "8.0" ]
                phpstan-level: [ 3, 5, 7, 8 ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                 php-version: ${{ matrix.php-version }}
                 tools: composer:v2, phpstan

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: PhpUnit
              run: bin/phpunit

            - name: Cs-Fixer
              run: |
                wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                chmod a+x php-cs-fixer
                  PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer fix src

            - name: PHPStan
              run: bin/phpstan analyze --level=${{ matrix.phpstan-level }} src

            - name: Infection
              run: |
                wget https://github.com/infection/infection/releases/download/0.20.0/infection.phar
                wget https://github.com/infection/infection/releases/download/0.20.0/infection.phar.asc
                chmod +x infection.phar
                ./infection.phar
