name: Quality

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                phpstan-level: [ 3, 5, 7, 8 ]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                 php-version: "8.0"
                 tools: composer:v2, phpstan

            - name: Install dependencies
              uses: php-actions/composer@v5

#    phpunit:
#        runs-on: ubuntu-latest
#        needs: [ build ]
#        steps:
            - name: PhpUnit
              run: bin/phpunit

#    cs-fixer:
#        runs-on: ubuntu-latest
#        needs: [ build ]
#        steps:
            - name: Cs-Fixer
              run: PHP_CS_FIXER_IGNORE_ENV=true bin/php-cs-fixer fix --dry-run src

#    phpstan:
#        runs-on: ubuntu-latest
#        needs: [ build ]
#        steps:
            -   name: PHPStan
                run: bin/phpstan analyze --level=${{ matrix.phpstan-level }} src

#    infection:
#        runs-on: ubuntu-latest
#        needs: [ phpunit, cs-fixer, phpstan ]
#        steps:
            - name: Infection
              run: |
                wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar
                wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar.asc
                chmod +x infection.phar
                ./infection.phar
