name: Quality

on: push

jobs:
    composer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP with pecl extension
                    uses: shivammathur/setup-php@v2
                    with:
                        php-version: '8.0'
                        tools: composer:v2, pecl

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.0

            -   name: Cs-Fixer
                run: |
                    wget -q https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                    chmod a+x php-cs-fixer
                    PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer fix src --dry-run

            -   name: Infection
                run: |
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar.asc
                    chmod +x infection.phar
                    pecl install pcov
                    ./infection.phar

            -   name: PHP Unit tests
                uses: php-actions/phpunit@v2
                with:
                    php_version: 8.0

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=8
