name: Quality

on: push

jobs:
    composer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            -   uses: php-actions/composer@v5
                with:
                    php_version: 8.0

    phpstan:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                phpstan-level: [ 3, 5, 7, 8 ]
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v5
                with:
                    php_version: 8.0

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=${{ matrix.phpstan-level }}

    phpunit:
        needs: composer
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v5
                with:
                    php_version: 8.0

            -   name: PHP Unit tests
                uses: php-actions/phpunit@v2
                with:
                    php_version: 8.0

    cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'

            -   name: Cs-Fixer
                run: |
                    wget -q https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                    chmod a+x php-cs-fixer
                    PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer fix src --dry-run

    infection:
        needs: composer
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v5
                with:
                    php_version: 8.0

            -   name: Infection
                run: |
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar.asc
                    chmod +x infection.phar
                    ./infection.phar
